### ISSUE TITLE
Node environment

### ISSUE THREAD

**Issue by ss-o** [z-shell/any-node#3]
https://github.com/z-shell/any-node/blob/518a893e9b117a91478996dfb5c3102880037a4e/package.json#L55

@devinrhode2,

I am not coming up with any ideas on how to set the node environment. However first you need to set ZI, so we might come to a conclusion :upside_down_face: This one is outdated and not adding the correct bin to PATH (so-called shim). It affects few packages only.

**Comment by devinrhode2** [comment]
I think integrating with Volta and/or asdf would be best. I prefer Volta due to the pinning feature.

**Comment by devinrhode2** [comment]
Volta is installed by adding a few binaries to the PATH

**Comment by devinrhode2** [comment]
I read through the readme it this project.

If it's extremely cheap and easy for each npm/node binary to have its own associated node version, that may be useful. It's not necessary in my experience, but there could be edge cases where only node 16 works with certain packages. Using latest lts will give you incredibly good reliability across the whole ecosystem, in my experience.

While I have a personal preference for Volta, other node version managers may be better suited for use in any-node.

**Comment by devinrhode2** [comment]
Which zsh packages depend on node?

**Comment by devinrhode2** [comment]
Depending on the nature of packages depending on node, it may be better for ZI to maintain it's own reference to latest node LTS.

If the binaries have any connection to actual local javascript projects, it will be better to try and leverage a pre-existing `node` install.

**Comment by devinrhode2** [comment]
As a front-end javascript/typescript/node developer, I think it's best for users to manage their own node install. And, I do think volta is a fine choice. Therefore, if node is not in PATH, then ZI would fail and recommend you install node via Volta.sh.

Does this align with your goals @ss-o?

I take it you need a reliable way to find npm binaries? (i.e. `npm install -g tsc`)

**Comment by ss-o** [comment]
You can view all packages here: https://github.com/z-shell/zpackages and they have a checkmark with uses node. (I'll assign topics to packages to navigate easier). And they are controlled by annex:

Bing-Gem-Node:
https://z.digitalclouds.dev/docs/ecosystem/annexes/bin-gem-node

Packages overview: 
https://z.digitalclouds.dev/docs/ecosystem/packages/packages-overview

For correct response, I have to review quite a lot, due to a lack of knowledge about the node itself. :juggling_person: It would be helpful if you get familiar with the basics and question me where required so we can align the knowledge gaps :octocat:.

**Comment by devinrhode2** [comment]
Feel free to add me to orgs/projects, sure

Because bin-gem-node doesn't modify system PATH, that implies it must be managing it's own node installation. 

Looking at the few packages that do use node, I think they are _significantly_ or _totally_ independent from any javascript project actually using node. This makes sense. Terminal doesn't really need to integrate deeply into node/javascript projects, could be useful one day, but not necessary now.

I'd assume bin-gem-node will use latest node LTS (v16.14.0 at time of writing).

I'll message you on twitter about when to connect :)

**Comment by ss-o** [comment]
Initially, the bin-gem-node annex was created having https://github.com/tj/n in mind. Which can be set set up with:

```shell
zi light-mode for as'program' atinit'export N_PREFIX="$HOME/n"; \
[[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"' pick"bin/n" \
    tj/n
```

> - Note - find easy with: https://z.digitalclouds.dev --> <kbd>CTRL+K</kbd> --> query.
> - Alternatively visit: https://z.digitalclouds.dev/search
